//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNot_Project_Raihan.ContentPages {
    
    
    public partial class Book {
        
        /// <summary>
        /// BookInfromation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNot_Project_Raihan.UsersContorl.BookInfromation BookInfromation;
    }
}
